name: CI

on:
  pull_request:
    branches: master

jobs:
  lint-black:
    name: black-formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Black
        run: |
          python -m pip install black
      - name: Black Code Formatter
        run: |
          black --check .

  lint-flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Flake8
        run: |
          python -m pip install flake8
      - name: Flake8 check
        run: |
          flake8 .

  lint-isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install isort
        run: |
          python -m pip install isort
      - name: isort check
        run: |
          isort --recursive --check-only .

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: false
          activate-environment: xcoare-test
          environment-file: ci/python-36.yaml
          channels: conda-forge
          allow-softlinks: true
          channel-priority: strict
          show-channel-urls: true
          use-only-tar-bz2: true
          python-version: ${{ matrix.python-version }}
      - name: Environment
        shell: bash -l {0}
        run: printenv | sort
      - name: Install package
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e .
      - name: Conda info
        run: |
          conda info
          conda list
      - name: Running Tests
        run: |
          conda activate xcoare-test
          python -m pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: test-reports/junit.xml
